### ISSUE TITLE
"Build status" badge in README - image is broken

### ISSUE THREAD

**Issue by tseemann** [phe-bioinformatics/PHEnix#1]
The badge doesn't appear for me, just some funny bold text link.

**Comment by alexjironkin** [comment]
That's a link to out internal CI that sits behind firewall. Ill can make it smaller but not go away. Sorry

**Comment by alexjironkin** [comment]
I'll look into moving the badge down to the bottom, because I appreciate its annoying  :)

**Comment by tseemann** [comment]
It just looks unprofessional to outsiders, and that is deserved!
