### ISSUE TITLE
Better memory usage for run_snp_pipeline.

### ISSUE THREAD

**Issue by alexjironkin** [phe-bioinformatics/PHEnix#12]
I've noticed that memory usage spikes a lot when processing VCF. Presumably this happens in filter VCF stage where all the records are kept. Then they are written to disk.

Instead, maybe we should have a parameter to `VariantSet.filter_vcf()` `outfile` if that is specified, then each record is written to the file as soon as it is filtered, thus reducing the memory footprint.

**Comment by alexjironkin** [comment]
Old record management : ![phoenix_pre](https://cloud.githubusercontent.com/assets/7687947/15669675/6d5a20d6-2719-11e6-8124-e8355948fac3.png)

New record management 
![phoenix](https://cloud.githubusercontent.com/assets/7687947/15669694/8798a3c8-2719-11e6-864b-66ae1159d360.png)

Useful side effect is that it took 6 mins instead of 60 mins (~10x speedup) for this sample. Anticipating this speedup to be translated to all other VCFs as well.

**Comment by antunderwood** [comment]
Nice work! This will be a big boon to running this on Galaxy. What are the mem requirements for vcf2fasta like?

**Comment by alexjironkin** [comment]
That's an interesting question. There are 2 parts to this:
- Reading all data into binary tree (BT).
- Concatenating bases together for samples.

Constructing BT is pretty good (we only store position and base + stats class for each position.
Concatenating can be a problem, because we do it for all samples in memory, then output to disk.

This is what it currently looks like for 1,2,3 and 4 samples:
![vcf2fasta-1](https://cloud.githubusercontent.com/assets/7687947/15670750/efc3f8a8-271e-11e6-977a-02b64a92c6fa.png)
![vcf2fasta-2](https://cloud.githubusercontent.com/assets/7687947/15670752/f552835c-271e-11e6-8e21-d8fc7e5b6eb3.png)
![vcf2fasta-3](https://cloud.githubusercontent.com/assets/7687947/15670754/f8a553ea-271e-11e6-9ae4-e619bbb3b38c.png)
![vcf2fasta-4](https://cloud.githubusercontent.com/assets/7687947/15670755/fb6c750e-271e-11e6-8c74-44d451604b39.png)

So ~170M for 4 samples worth of VCF data, then another ~180M for FASTA data. But this will be impacted on how similar/diverse your sequences are. In the fourth graph it looks like one of the samples is somewhat distant from others because we suddenly need a lot more memory for 2nd phase. 

Conceptually we can make it faster by:
- Create parallel reader for VCF that will go through the individual VCFs in position order and will output one position at a time from all VCFs. That means we can get all data per position from all samples and output it. But we won't be able to do --sample-Ns (or have to do something else)
- For second phase we can output FASTA data into separate files, then concatenate them. This means we can do it in parallel and without heavy footprint in second phase.

**Comment by alexjironkin** [comment]
I re-ran the memory profiler with **FASTA** output **turned off** and got the following:

![vcf2fasta-4-novcf](https://cloud.githubusercontent.com/assets/7687947/15671028/79268722-2720-11e6-9ed7-756f4541b825.png)

it seems like the memory usage of the BT is much higher than I previously thought. Maybe 95-5 split between 2 phases. re-jigging the first phase would have higher impact on overall performance of the vcf2fasta converter.

**Comment by alexjironkin** [comment]
I have an implementation of that optimises the memory usage a little better for vcf2fasta and the preliminary results look encouraging:
![vcf2fasta-4-new](https://cloud.githubusercontent.com/assets/7687947/15679695/aca99e98-274a-11e6-82b9-e1ae92eac17e.png)

The wiggles are the FASTA sequences concatenated in memory.

**Comment by alexjironkin** [comment]
complete implementation looks something like this.

![new-vcf2fasta2](https://cloud.githubusercontent.com/assets/7687947/15747827/6431effe-28d4-11e6-9a2c-730194ef1fa5.png)

It should be more or less constant with input size (number of VCFs.  Full reference export is a little more expensive (especially at the end where full reference is read back in). But this can be done now on laptops without trouble, as far as memory goes.

![new-vcf2fasta](https://cloud.githubusercontent.com/assets/7687947/15747709/e91893b8-28d3-11e6-9c81-155da3832f3b.png)

I had to implement parallel file writer for multiple VCFs, this comes at a cost of having to comply with OS ulimit setting (set to 1024 on many platforms).
