### ISSUE TITLE
shebang and executable on run_snp_pipeline.py

### ISSUE THREAD

**Issue by antunderwood** [phe-bioinformatics/PHEnix#17]
Should run_snp_pipeline.py have the shebang #!/usr/bin/env python  and be executable?

**Comment by antunderwood** [comment]
ditto prepare_reference.py? and others?

**Comment by ulfschaefer** [comment]
phenix.py has a shebang and is executable. The other scripts are reachable as a subcommand do phenix.py as in phenix.py run_snp_pipeline -h, etc. Therefore only phenix.py needs to be executable, I think.

**Comment by gkapatai** [comment]
Ah ok  - in that case the doc needs updating:
http://phenix.readthedocs.io/en/latest/Calling%20SNPs.html

**Comment by antunderwood** [comment]
Ah ok - in that case please can the doc needs be updated:
http://phenix.readthedocs.io/en/latest/Calling%20SNPs.html
