### ISSUE TITLE
Options -m and -v not recognised

### ISSUE THREAD

**Issue by gkapatai** [phe-bioinformatics/PHEnix#19]
Running this command: 

`phenix.py prepare_reference -v gatk -m bowtie2 -r reference.fasta`

returned this error: phenix.py: error: unrecognized arguments: -v gatk -m bowtie2

When command changed to: 

`prepare_reference --variant gatk --mapper bowtie2 -r reference.fasta`

it worked fine.

**Comment by alexjironkin** [comment]
Where does it mention to run prepare_reference with `-v` and `-m` options?

**Comment by ulfschaefer** [comment]
As per the help and the documentation the shortened version of the parameters are not available for these options. 

usage: phenix.py prepare_reference [-h] --reference REFERENCE
                                   [--mapper MAPPER] [--variant VARIANT]

Prepare reference for SNP pipeline by generating required aux files.

optional arguments:
  -h, --help            show this help message and exit
  --reference REFERENCE, -r REFERENCE
                        Path to reference file to prepare.
  --mapper MAPPER       Available mappers: ['bwa', 'bowtie2']
  --variant VARIANT     Available variants: ['mpileup', 'gatk']
