### ISSUE TITLE
Confusion over name - PHEnix or Phoenix ?

### ISSUE THREAD

**Issue by tseemann** [phe-bioinformatics/PHEnix#2]
The repo is called `PHEnix` but the docs call it `Phoenix`.

And the repo doesn't have a runnable command called either of those? eg. `phenix`

**Comment by alexjironkin** [comment]
We do not have a runnable `phenix.py` command in favour of more appropriately named scripts in the scripts directory. 

If used in python to import modules we felt its also more appropriate and readable to have statement like `import phe.mapping` instead of `import phe.phenix.mapping`.

Thanks for the notice on the docs not correctly reflecting the name in the repo. @all can we correct the docs.

**Comment by tseemann** [comment]
I would rename your two main scripts to `phenix-prepare_reference` and `phenix-run_blah` etc, or have a single `phenix` script with sub-commands (like `samtools` and `sga` etc).

You want to avoid name clashes, and it provides a single place to get a `--version` option.

As per https://gigascience.biomedcentral.com/articles/10.1186/2047-217X-2-15 ;-)

**Comment by antunderwood** [comment]
I think that could work nicely. We'll look into it and maybe use the nesting parsers feature of argparse (https://pymotw.com/2/argparse/#nesting-parsers).

**Comment by alexjironkin** [comment]
Just added phenix.py with the command subparsers.

Have not implemented `--version` option yet, as there is an ongoing discussion on how to make in universal from git/pip. I have used [versioneer](https://github.com/warner/python-versioneer) in the past and like it. But I am not certain yet if this is the most appropriate way of doing it yet. It's coming though.

**Comment by antunderwood** [comment]
It would be good to transfer the updated instructions reflected in readthedocs to the README.md

**Comment by alexjironkin** [comment]
No need, it's automatically done via the docs build system:

http://phenix.readthedocs.org/en/latest/scripts/modules.html

**Comment by antunderwood** [comment]
The README.md on the front page still reflects the old way of calling the scripts

**Comment by alexjironkin** [comment]
Oh yeah, totally forgot about that. :)

**Comment by tseemann** [comment]
Looking professional now! 👍

**Comment by alexjironkin** [comment]
`--version` is there now. It is also in the VCF headers for future reference. I had to ditch cool git version string in favour of more simplistic approach. Mostly due to difficulties in getting it done decently in different places.
