### ISSUE TITLE
Don't use file handles to store data

### ISSUE THREAD

**Issue by alexjironkin** [phe-bioinformatics/PHEnix#21]
Currently, `vcf2fasta` stores the SNP data for each sample in a separate file. While this means that little memory is required to process large number of files, it is limited by default open file handle limit (usually 1024). 

We need to move away from this to a different system. For example, open file handles with **append** and write one character. While this is not ideal, and limits the throughput by the disk I/O it is more preferential than having to increase the file handle limit.

**Comment by tseemann** [comment]
Possibly consider an SQLite database?

**Comment by alexjironkin** [comment]
Don't want introduce a dependency that's not necessary and too much for what this needs. 

Thanks for the suggestion though.

**Comment by ulfschaefer** [comment]
We have to moved away from this to a different system. vcf2fasta now parses each vcf and stores only minimal variants position lists.
