### ISSUE TITLE
Add, 'add to pythonpath' to instructions

### ISSUE THREAD

**Issue by flashton2003** [phe-bioinformatics/PHEnix#22]
For me, the PHEnix directory needs to be added to the pythonpath for the imports to work.

**Comment by alexjironkin** [comment]
Did you install using pip/python setup.py install?

**Comment by tseemann** [comment]
Does it work with `pip install --user <repo.git>` ?

**Comment by alexjironkin** [comment]
Install should work with Torsten's command as well. Otherwise, if you just download the code, you will need to add the directory where you have downloaded it to:

```
PYTHONPATH=$PYTHONPATH:<download dir>
```

**Comment by tseemann** [comment]
@flashton2003 if you use the `pip install --user` method your executables will end up in `$HOME/.local/bin` I think. You will need to add that to your `$PATH` in `.bash_profile` etc.

**Comment by flashton2003** [comment]
yeah, i did the install with `pip install -e PHEnix`

i got it working, the only point was that, following the instructions, it didnt work, so maybe add the pythonpath bit to the instructions?

:-)
