### ISSUE TITLE
why is parse vcf so slow?

### ISSUE THREAD

**Issue by flashton2003** [phe-bioinformatics/PHEnix#27]
It just took 35 minutes just to filter the vcf (19 Mbp genome), why is it so slow?

I also get exactly the same performance with and without FastBinaryTree.

**Comment by alexjironkin** [comment]
19Mb sounds low, is this a VCF with all bases emitted? We had to include check for missing data because mpileup doesn't emit all sites. 

If your filtered VCF contains lots of ./. calls, then this happened. Can you check that please.

**Comment by flashton2003** [comment]
The genome is 19 Mbp, the vcf is over a gig

**Comment by alexjironkin** [comment]
Is there lots lots of ./. genotypes?

**Comment by flashton2003** [comment]
No, not particularly. There are around 500 000 ./. which is around 2% of the genome. Proportionally less than typical Salmonella.
