### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by tseemann** [phe-bioinformatics/PHEnix#3]
I can't find any install guide in README.md or ReadTheDocs.

Maybe explain how to git clone and use pip (pip2 or pip3?) etc

I did this and it seemed to work

```
git clone https://github.com/phe-bioinformatics/PHEnix.git
pip2  install -e PHEnix
```

**Comment by alexjironkin** [comment]
I got a feeling that if you do `pip freeze` it will currently list PHE-phoenix as well instead of PHE-phenix

**Comment by alexjironkin** [comment]
I included a section on installation and updated the setup.py to reflect project name better. 

http://phenix.readthedocs.org/en/latest/Introduction.html#installation
