### ISSUE TITLE
Issue Running PHEnix on CentOS7 build

### ISSUE THREAD

**Issue by Andybacon76** [phe-bioinformatics/PHEnix#30]
Hi There I have install PHEnix (using this command pip install git+https://github.com/phe-bioinformatics/PHEnix.git) on a CentOS7 machine, also installed the Prereqs as per instructions. when i run the below command:
phenix.py prepare_reference.py --mapper bwa --variant gatk --reference Downloads/*****_stx/*****_O157.fa i get the below error. can you advise?
Traceback (most recent call last):
  File "/usr/bin/phenix.py", line 14, in <module>
    import filter_vcf
  File "/usr/bin/filter_vcf.py", line 13, in <module>
    from phe.variant import VariantSet
ImportError: No module named phe.variant

**Comment by ulfschaefer** [comment]
Hi, it looks like you need to add the installation location to your PYTHONPATH environment variable.

**Comment by jb2cool** [comment]
I work with Andy and we did think about this as it was also mentioned in Issue:22 but where is the install location? Some bits are in /usr/bin but where else should we be looking?

If i do the pip install from source i don't seem to get this error (But i got other errors that i need to investigate similar to Issue:25)

**Comment by ulfschaefer** [comment]
The executables will go into /usr/bin, but the libraries would go into the site-packages area of your python installation. Not sure where exactly that would be on your CentOS machine. It's the site-packages that need to go into the PYTHONPATH.

**Comment by jb2cool** [comment]
ah understood, thanks. Will give that a shot. Still don't really understand why we get different results with each of the install methods though.

/usr/lib/python2.7/site-packages and /usr/lib64/python2.7/site-packages are where they live for me.
