### ISSUE TITLE
Add to README `pip install` directly from `github`

### ISSUE THREAD

**Issue by andersgs** [phe-bioinformatics/PHEnix#31]
Hi.

One can install directly from `github` without cloning the repo:

`pip install git+https://github.com/phe-bioinformatics/PHEnix.git`

The user can install with:

`pip install --user git+https://github.com/phe-bioinformatics/PHEnix.git`

A specific version or tag can be installed with:

`pip install git+https://github.com/phe-bioinformatics/PHEnix.git@my_tag`

Cheers.

Anders.

**Comment by tseemann** [comment]
@andersgs pip2 or pip3 ?
