### ISSUE TITLE
Can PHEnix output consensus genome?

### ISSUE THREAD

**Issue by flashton2003** [phe-bioinformatics/PHEnix#35]
Definitely a feature request not a bug, it would be great if PHEnix could output the reference genome, modified with the variants in the VCF. 'Mutate' the reference genome with the appropriate SNPs from the VCF, replace regions with <5 depth, <30 MQ with Ns or '-'.

These consensus genomes could then be fed into e.g. snp-sites/gubbins for easy analysis.

Would you accept a pull request adding this feature in?

**Comment by ulfschaefer** [comment]
Can Phenix not already do that, kind of? Using vcf2fasta with only one vcf and the reference. You get a fasta file with two complete sequences, the consensus and the reference. All you need to do is take the reference out.

**Comment by flashton2003** [comment]
Ok, I'll look into it. Thanks Ulf.

**Comment by flashton2003** [comment]
So, I generated 30 consensus genomes using the vcf to fasta method and passing the reference sequence. However, the length of the output consensus for different samples is not equal, it varies by a few hundred bases from isolate to isolate.

I tried three command lines. These two gave the same results of uneven lengths of consensus sequence.

`phenix.py vcf2fasta -i /home_dir/phil_tmdata/11CN-03-065/phenix/test_sample.filtered.vcf  -o /home_dir/phil_tmdata/11CN-03-065/phenix/test_sample.fasta --reference /home_dir/references/2017.12.04/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.fasta --column-Ns 1 --column-gaps 1 --sample-Ns 1 --sample-gaps 1`

`phenix.py vcf2fasta -i /home_dir/phil_tmdata/11CN-03-003/phenix/test_sample.filtered.vcf  -o /home_dir/phil_tmdata/11CN-03-003/phenix/test_sample.2.fasta --reference /home_dir/references/2017.12.04/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.fasta`

And then I tried passing two vcfs at the same time, but this produced an OSError. 

`phenix.py vcf2fasta -i /home_dir/phil_tmdata/11CN-03-003/phenix/test_sample.filtered.vcf /home_dir/phil_tmdata/11CN-03-002/phenix/test_sample.filtered.vcf -o /home_dir/test_sample.fasta --reference /home_dir/references/2017.12.04/GCA_000001985.1_JCVI-PMFA1-2.0_genomic.fasta`

`Traceback (most recent call last):
  File "/home/biodocker/bin/PHEnix/scripts/phenix.py", line 113, in <module>
    exit(main())
  File "/home/biodocker/bin/PHEnix/scripts/phenix.py", line 105, in main
    return vcf2fasta.main(args)
  File "/home/biodocker/bin/PHEnix/scripts/vcf2fasta.py", line 592, in main
    os.unlink(args["out"])
OSError: [Errno 2] No such file or directory: '/home_dir/test_sample.fasta'`

**Comment by ulfschaefer** [comment]
Hi Phil. Just from the line numbers in your traceback I can tell that you are not using the latest version. I think the "os.unlink(args["out"])" line was removed from vcf2fasta when I rewrote it. Can you get the latest release (1-4) and try again?

**Comment by flashton2003** [comment]
ok thanks, will check it out.
