### ISSUE TITLE
prepare_reference.py doesn't do anything?

### ISSUE THREAD

**Issue by tseemann** [phe-bioinformatics/PHEnix#4]
```
% ls
file.fa

% prepare_reference.py  --ref file.fa

% ls
file.fa
```

The `--mapper` and `--variant` are optional?

Would be very useful to print some information to `stderr` to see what is going on.

When I add `--mapper bwa` it seems to run `bwa index` and blats my current directory, and prints nothing?

**Comment by alexjironkin** [comment]
In that case nothing went on, because you didn't specify anything. But I'll update the docs and group arg parser for requirements. Plus extra logging for prepping a reference

**Comment by alexjironkin** [comment]
More verbose output there is now provided by `prepare_reference.py`
