### ISSUE TITLE
Change pip to pip2 in README

### ISSUE THREAD

**Issue by tseemann** [phe-bioinformatics/PHEnix#42]
Use `pip2` instead of `pip` 
```
$ pip install git+https://github.com/phe-bioinformatics/PHEnix.git
$ pip install PHEnix
```
This is to avoid problems where `pip` has been over-written by `python3` installer.

**Comment by ulfschaefer** [comment]
Yup, sure. Good point. 3c7c3fe7a9253bc4cd1df545971291a6a9940866
