### ISSUE TITLE
Strict requirements for old version of numpy?

### ISSUE THREAD

**Issue by russellsmithies** [phe-bioinformatics/PHEnix#43]
We're having problems with the strict requirement for an old version of numpy ('numpy<1.12.0,>=1.11.0' ) that prevents many other applications running (eg srst2, snapperdb etc). Do you actually need such an old version of numpy or could you manage with the current? The alternative is we stop using PHEnix :-(

**Comment by tseemann** [comment]
Russel, i am not an author of PHEnix but you have a few options.

1. Use `virtualenv`, `pyenv` etc to have separate environments for each big app

2. After you git clone PHEnix, just edit the `requirements.txt` file and change the numpy line. eg. https://github.com/phe-bioinformatics/PHEnix/blob/master/requirements.txt and see if it works!

3. Try an alternative SNP caller, for example 
  * `snippy` https://github.com/tseemann/snippy  (my tool)
  * `nasp`
  * `snp-pipeline`

**Comment by Wang-Jing-NZ** [comment]
Thank you, Torsten, for your reply. I will try to snippy and GATK outputs first. 

Cheers
Jing

**Comment by ulfschaefer** [comment]
Before you abandon the goodness that is PHEnix for brighter shores ...

This is a case of not tidying up. The requirement for numpy can be removed. The code used to call mean and std from numpy, but it does not appear to do so any more.

https://github.com/phe-bioinformatics/PHEnix/commit/68d35c27ed7a90c2c88ee522a3d7b0a7e2dade9f

And sorry for the late reply. Let me know if you have any problems with this. I will reply faster now.

**Comment by russellsmithies** [comment]
All sorted now I think, we'll do a bit more testing to confirm :-)
