### ISSUE TITLE
SNP filtering really slow

### ISSUE THREAD

**Issue by BertBog** [phe-bioinformatics/PHEnix#44]
Dear,

Is there a way to decrease the time it takes to do the SNP filtering?
The read mapping and variant calling steps are typically really quick, but the SNP filtering takes a huge amount of time (>100 times more than the other steps), which unfortunately makes it really hard for us to use this pipeline.

This is the command than I use:

`phenix.py run_snp_pipeline --reference /scratch/bebog/working/phylo/NC_002695.2.fasta -r1 /scratch/VTEC_SN/xxAZJpmiBhmmjKkSxAHw_L001_R1_001.fastq.gz -r2 /scratch/VTEC_SN/xxAZJpmiBhmmjKkSxAHw_L001_R2_001.fastq.gz --sample-name "test_sample" --outdir /scratch/working/phylo --mapper bwa --variant gatk --mapper-options "-t 20" --variant-options "-nt 10 -ploidy 1" --keep-temp --filters min_depth:5,mq_score:30,min_depth:10,ad_ratio:0.90
[2018-09-21 09:43:23,145] INFO: Version: 1-4
[2018-09-21 09:43:23,145] INFO: Initialising data matrix.
[2018-09-21 09:43:23,150] INFO: Mapping data file with bwa.
[2018-09-21 09:44:49,393] INFO: Creating digitised variants with gatk.
[2018-09-21 09:45:15,557] INFO: Applying filters: ['mq_score:30', 'min_depth:10', 'ad_ratio:0.9']`

Best regards,
Bert

**Comment by ulfschaefer** [comment]
Dear Bert
When I run it (also on an E.coli O157), I get the following times:
Mapping: 7 minutes
Variant calling: 13 minutes
Filtering: 5 minutes
Total: 25 minutes
I run everything on a single CPU thread and I don't think I was the only one using the machine at the time. Since you are running the mapping on 20 threads and the variant calling on 10 threads, your timings for those more or less make sense. The filtering is not parallelised. It's a Python script that parses the all-positions vcf file and takes a few minutes.
Am I understanding you correctly that your filtering takes more than an hour and a half? Is this consistent across more than one environment?
Thanks
Ulf

**Comment by BertBog** [comment]
Hi,

Thanks for your response.
My original run was on a Ubuntu 16.04 machine with Python 2.7.6
I'm having the same problem on a clean install Ubuntu 18.04 with Python 2.7.15.

I think the problem is caused by the 'filter_variants' functions in the __init__.py file located under 'phe/variant'. I added some logging statements to this function and it seems that the loop takes slightly longer on every iteration. 

From my tests:
First 500 positions: ~ 0.20 seconds per 500 positions
After 10.000 positions: ~0.30 seconds per 500 positions
After 100.000 positions: ~1.33 seconds per 500 positions
After 150.000 positions: ~2.21 seconds per 500 positions
So after a while the process gets extremely slow.

Which python version and what versions of Biopython & PyVCF do you use? Maybe it could be related to this.

Best regards,
Bert

**Comment by ulfschaefer** [comment]
I am using Biopython v1.68 and PyVCF v0.6.8. Not sure if that would make a difference.

For me the timings in the loop stay quite constant throughout (at about 0.27sec per 5000 iterations). But memory usage increases steadily, reaching 1.3GB at the end. Is it possible you don't have enough free memory? If it runs out and starts using the swap space it will be very slow indeed.

**Comment by BertBog** [comment]
I use 1.69 and 0.6.8 so this is indeed not the problem. I downgrade biopython just to be sure, but this did not solve it. 

I also checked the memory and this does not seem to be the issue either, it already slows down even when there is over 100 gb of free memory available.

Strangely enough on my system the memory does not cap out, it is steadily increasing as the program is running. I'm currently at 2.9 gb after 200.000 positions.

**Comment by BertBog** [comment]
I just did some profiling using cProfile
And it seems to be that the slow down is caused by the repeated namedtuple calls in the PyVCF code. 
I'm not sure how this can be easily fixed. And it is very strange that this does not affect your own systems.

Here is the output of the profiling (line numbers might be slightly off due to my debugging statements):
ncalls | tottime | percall | cumtime | percall filename:lineno(function)
170966 | 54.644 | 0 | 401.979 | 0.002 collections.py:288(namedtuple)
1 | 5.305 | 5.305 | 420.63 | 420.630 __init__.py:128(filter_variants)
170950 | 3.863 | 0 | 406.108 | 0.002 model.py:662(make_calldata_tuple)

This is the line that leads to the namedtuple calls:
record = vcf.model._Record(record.CHROM, _pos, ".", _ref, [None], 0, [], {}, 'GT', None)

Best regrads,
Bert

**Comment by ulfschaefer** [comment]
Do you use the c bindings for PyVCF? You get them if you install cython before you install PyVCF. Maybe this is the difference between our systems and a way to fix it?

**Comment by BertBog** [comment]
Is there any quick way to check this?
I don't get any of the warnings below, but I do not think the phenix.py really checks them?
```
Warning: FastBinaryTree not available, using Python version BinaryTree.
Warning: FastAVLTree not available, using Python version AVLTree.
Warning: FastRBTree not available, using Python version RBTree.

```
I've also reinstalled it with:
```
pip2 uninstall PyVCF
pip2 uninstall bintrees
pip2 install cython
pip2 install PyVCF bintrees
```

But they are still slow, but I'm not sure if the Cbindings for PyVCF are actually used, because the debugging statement that I put in the PyVCF model.py source code is still executed.

**Comment by ulfschaefer** [comment]
These warnings used to be issued by bintrees, but I think later versions don't issue it any more. If I go to my bintrees code folder `lib/python2.7/site-packages/bintrees` I find a file `cython_trees.so`. There is also a method to test it for bintrees:


>>> import bintrees
>>> bintrees.has_fast_tree_support()
True

For PyVCF there is no method to test it, as far as I can see, but on one machine I have a file `cparse.so` in `lib/python2.7/site-packages/vcf` and on a test box where I never installed Cython I don't have this file.

**Comment by BertBog** [comment]
I reinstalled and verified that all the files you mentioned were present.
Also for bintrees fast trees was enabled.

```
python2 -c "import bintrees; print(bintrees.has_fast_tree_support())"
>>> True
```
But it is still as slow as before. I have no clue what the reason is.

Could you maybe run on the same data file as me if you have the time?
[test_sample_phe.zip](https://github.com/phe-bioinformatics/PHEnix/files/2420417/test_sample_phe.zip)

I use the command:
`phenix.py filter_vcf --vcf test_sample_phe.vcf --output tmp --filters mq_score:30,min_depth:10,ad_ratio:0.9`

I had to modify the __init__.py file of the variant module because this line throws an error when using this command. The following line of code leads to the crash:
`var_set.filter_variants(out_vcf=args["output"], only_good=args["only_good"])  
TypeError: filter_variants() got an unexpected keyword argument `'out_vcf'`
`
```
def filter_variants(self, keep_only_snps=False, only_good=False):
-> 
def filter_variants(self, keep_only_snps=False, only_good=False, out_vcf=None):
```

For the rest the code is exactly the same as in the repo.

**Comment by ulfschaefer** [comment]
Hi Bert

The area of the code that causes the slowdown seem to be the bit that deals with missing positions in your vcf file. In our pipeline we use Phenix to filter all-positions vcf file, so there is one record per position in the reference, and this bit of code is used on rare occasions only.

Your vcf only has ~500 records in it, so it has to call this record creation millions of times.

Your sample has been running for 45 minutes when I killed it, a all-position vcf from O157 finished the same command in 5 minutes.

Hope this helps, not sure how your pipeline is set up.
Ulf

**Comment by BertBog** [comment]
Allright, you were right its faster starting from the complete VCF files.
I think the issue can be closed. It's still a bit worrying that PyVCF uses this very inefficient way of instantiating a novel namedtuple classes each time a record is created, so I might open an issue there.
Thanks a lot for helping me with this.
