### ISSUE TITLE
Is public release mirroring PHE version?

### ISSUE THREAD

**Issue by flashton2003** [phe-bioinformatics/PHEnix#45]
Hi guys,

I'm sure you're super busy with other stuff right now, but I was just wondering if the public release version of PHEnix is still matching with the internal PHE version. Just that there have been no commits to this repo for around 18 months.

Ta!

Phil

**Comment by ulfschaefer** [comment]
Phil!

Not exactly a mirror. But there haven't been any massive developments. Just readme and modulefile stuff mostly. Anything not working?

Thanks
Ulf

**Comment by flashton2003** [comment]
Ulf! 

Ok, that's great. Just wanted to make sure you hadn't found some horrible bugs and forgotten to push to github :-)

Thanks!

Phil
